[package]
name = "gameboy_emulator"
version = "0.1.0"
authors = ["Trangar <victor.koenders@gmail.com>"]
edition = "2018"

[dependencies]
minifb = "0.14"
drawille = "0.2"
structopt = "0.3"
terminal_size = "0.1"

